### ISSUE TITLE
1.14.2 - Error on player login

### ISSUE THREAD

**Issue by fjeddy** [crashdemons/AztecTabCompleter#10]
Everytime a player is entering the server on 1.14.2 it spits out an error.

```
[19:46:13] [Server thread/ERROR]: [AztecTabCompleter] Unhandled exception occured in onPacketSending(PacketEvent) for AztecTabCompleter 
java.lang.UnsupportedOperationException: The method hasPermission is not supported for temporary players.                               
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[?:?]            
        at com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$3e5fc49b.hasPermission(<generated>) ~[?:?]          
        at com.github.crashdemons.aztectabcompleter.AZTabPlugin$1.onPacketSending(AZTabPlugin.java:98) ~[?:?]                           
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]     
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]       
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]                        
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]                 
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]                        
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]                     
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) ~[?:?]                        
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) ~[?:?]                             
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) ~[?:?]                     
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) ~[?:?]                  
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]                        
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]                                  
        at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:208) ~[patched_1.14.2.jar:git-Paper-66]                   
        at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:171) ~[patched_1.14.2.jar:git-Paper-66]          
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1553) ~[patched_1.14.2.jar:git-Paper-66]              
        at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1526) ~[patched_1.14.2.jar:git-Paper-66]     
        at net.minecraft.server.v1_14_R1.CommandDispatcher.a(CommandDispatcher.java:266) ~[patched_1.14.2.jar:git-Paper-66]             
        at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:906) ~[patched_1.14.2.jar:git-Paper-66]                           
        at net.minecraft.server.v1_14_R1.PlayerList.d(PlayerList.java:757) ~[patched_1.14.2.jar:git-Paper-66]                           
        at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:167) ~[patched_1.14.2.jar:git-Paper-66]                           
        at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:169) ~[patched_1.14.2.jar:git-Paper-66]                     
        at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.2.jar:git-Paper-66]                   
        at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:255) ~[patched_1.14.2.jar:git-Paper-66]                   
        at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.2.jar:git-Paper-66]               
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1201) ~[patched_1.14.2.jar:git-Paper-66]                
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-66]                 
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-66]                
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-66]               
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]                                                                          
```

**Comment by crashdemons** [comment]
Which version of plugin are you using?

**Comment by crashdemons** [comment]
Also, if you're using an older version, please try out 0.20.3:
https://ci.meme.tips/job/AztecTabCompleter/

**Comment by fjeddy** [comment]
@crashdemons I'm running the last "release", noticed that the two after that is marked "Alpha release", considered updating, but figured I should wait.

Are they safe to use?

NVM: See now you just made it a release instead of a pre-release. Updating and testing; will let you know.

**Comment by crashdemons** [comment]
0.20.3 should be safe, we've been live-testing it on our server for quite a while.
And more stable since it doesn't use ProtocolLib anymore.

**Comment by fjeddy** [comment]
Updated, only have two players and myself to test with at this hour. But so far so good, no errors as of yet. Think we can just close this and I will just let you know if it happens again :)

Thank you very much for the assistance.
